name: first_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  url_launcher: ^5.4.1
  cupertino_icons: ^0.1.2
  open_file: ^2.0.0 
  flutter_pdfview: ^1.0.0+10
  path_provider: ^1.5.1
  google_maps_flutter: ^0.5.21+15
  json_serializable: ^3.2.5
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - images/Ahtapot/
    - images/Diamond1-5m3/
    - images/Diamond2m3/
    - images/Diamond3m3/
    - images/Hammer/
    - images/Orkinos870/
    - images/Orkinos1270/
    - images/Pelican4m3/
    - images/Pelican6m3/
    - images/Pelican8m3/
    - images/Piranha/
    - images/Scorpion/
    - images/Super8002EDUAL/
    - images/Super8002EDUAL/
    - images/SuperS8002/
    - images/SuperS8002E/
    - images/SuperYunus/
    - images/SuperYunus3Yabali/
    - images/SuperYunusDual/
    - images/SuperYunusDual2/
    - images/Yengec/
  fonts:
  - family: Raleway
    fonts:
    - asset: fonts/Raleway-Regular.ttf
    - asset: fonts/Raleway-Bold.ttf
    - asset: fonts/Raleway-ExtraBold.ttf
    - asset: fonts/Raleway-Italic.ttf
      style: italic

